echo FROM python:3.11-slim > Dockerfile
echo. >> Dockerfile
echo WORKDIR /app >> Dockerfile
echo. >> Dockerfile
echo COPY requirements.txt . >> Dockerfile
echo RUN pip install --no-cache-dir -r requirements.txt >> Dockerfile
echo. >> Dockerfile
echo COPY src/ ./src/ >> Dockerfile
echo. >> Dockerfile
echo RUN python -c "import click; print(f'Click version: {click.__version__}')" >> Dockerfile
echo. >> Dockerfile
echo CMD ["python", "-m", "src.main", "--help"] >> Dockerfile